description: "Configurations for AgentSearchBench generation pipeline."

# Task Generation
gen_model: gpt-5.2      # defined in models.yaml
n_tasks: 1
# Multi-Agent Task Query
n_agents: [2, 3, 4]
# Task Description
n_subtasks: 5
sample_pool_size: 10
coherence_threshold: 0.75
n_criteria: 2           # ~(n_subtasks / 2)

# Candidate Selection
n_candidates: 5  
selector_models:        # defined in models.yaml
  bm25: 1.0
  bge: 1.0
  toolret: 1.0
# Response Generation
active_platforms:       # defined in models.yaml
  - agentainetwork
  # - openaiagents
# Judging
judge_models:           # defined in models.yaml
  - gpt-5.2
  # - gemini-2.5-pro
  # - qwen-3-32B
use_golden_labels: false
judge_token_limit: 4000
# Labels
qrel_type: binary
rank_label_type: finegrain
relevance_threshold: 4
